# Generated by Django 4.1.2 on 2022-10-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inspections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("inspectorName", models.CharField(max_length=100)),
                ("itemsOk", models.IntegerField()),
                ("issuesWarningCount", models.IntegerField()),
                ("issuesCriticalCount", models.IntegerField()),
                ("company", models.CharField(max_length=100)),
            ],
        ),
    ]
